### ISSUE TITLE
release new version on updates

### ISSUE THREAD

**Issue by hans-d** [cloudposse/github-action-docker-build-push#55]
With the recent commits (dependency updates), no new version is released. Pref this should be automated, like with atmos/geodesic.

**Comment by hans-d** [comment]
to be able to use
https://aws.amazon.com/blogs/containers/announcing-remote-cache-support-in-amazon-ecr-for-buildkit-clients/

**Comment by korenyoni** [comment]
> With the recent commits (dependency updates), no new version is released.

We've recently discovered that broken tests in this repo have short-circuited our automated releases, which were already in place. This has been fixed by https://github.com/cloudposse/github-action-docker-build-push/pull/74.

As for remote cache support, this action supports it now and has the following documented:

https://github.com/cloudposse/github-action-docker-build-push/blob/ebc5e80a31a33a5c49f6e81335dc440f308a1ec8/README.md?plain=1#L76-L86
